export interface CameraMonitorStatus {
  instrument: string;
  state: "stopped" | "running" | "failed";
  connected: boolean;
  camera_id: number | null;
  lease_id?: string | null;
  lease_expires_at?: number | null;
  subscriber_count?: number;
  requested_resolution: { width: number; height: number } | null;
  actual_resolution: { width: number; height: number } | null;
  requested_pixel_format: string | null;
  actual_pixel_format: string | null;
  frame_id: number | null;
  received_at: number | null;
  frame_age_seconds: number | null;
  image_url: string | null;
  control_fingerprint: string | null;
  capture_profile?: Record<string, unknown> | null;
  run_id: string | null;
  campaign_id: string | null;
  trial_number: number | null;
  step_index: number | null;
  step_command: string | null;
  step_substep: string | null;
  expected_well: string | null;
  expected_center?: { x: number; y: number } | null;
  expected_center_source?: string | null;
  well_identity_verification: "not_verified_by_cv";
  roi: Record<string, unknown> | null;
  quality: Record<string, unknown> | null;
  processing_profile: Record<string, unknown> | null;
  analysis_source_image_path?: string | null;
  analysis_image_url?: string | null;
  analysis_source_run_id?: string | null;
  analysis_source_well?: string | null;
  analysis_source_frame_id?: number | null;
  analysis_source_received_at?: number | null;
  analysis_is_current_frame?: boolean;
  latest_analysis?: Record<string, unknown> | null;
  warnings: string[];
  error: string | null;
}
